### ISSUE TITLE
Problem with Python>3.7 [MACOS]

### ISSUE THREAD

**Issue by vitormhenrique** [garretfick/pydnp3#7]
I can't get pydnp3 running on my computer (and the server, MacOS) if I use the library with Python>3.7.

It works fine on 3.6 but the same code hangs on newer python versions, I tried to compile with newer versions of pybind11 but no luck.

Weird thing is that it works on ubuntu on python 3.8.5 just fine!

I have the following dnp3_master.py

```
from pydnp3 import opendnp3, openpal, asiopal, asiodnp3
import time
import logging

class SOEHandler(opendnp3.ISOEHandler):
    
    def __init__(self):
        self._values ={'analog': [],'binary': []}
        super(SOEHandler, self).__init__()

    def Process(self, info, values):
        a_vals = []
        b_vals = []
               
        if (type(values) == opendnp3.ICollectionIndexedAnalog):
            class BOSVisitor(opendnp3.IVisitorIndexedAnalog):
                def __init__(self):
                    super(BOSVisitor, self).__init__()
                def OnValue(self, indexed_instance):
                    a_vals.append(indexed_instance.value.value)
            values.Foreach(BOSVisitor())
            self.values['analog'] = a_vals.copy()

        if (type(values) == opendnp3.ICollectionIndexedBinary):
            class BOSVisitorBin(opendnp3.IVisitorIndexedBinary):
                def __init__(self):
                    super(BOSVisitorBin, self).__init__()
                def OnValue(self, indexed_instance):
                    b_vals.append(indexed_instance.value.value)
            values.Foreach(BOSVisitorBin())
            print("here")
            self.values['binary'] = b_vals.copy()


    def Start(self):
        # This is implementing an interface, so this function
        # must be declared.
        pass

    def End(self):
        # This is implementing an interface, so this function
        # must be declared.
        pass



class Dnp3_Master():
    
    _values ={'analog': [],'binary': []}

    def _setValues(self, values):
        self._values = values

    def _getValues(self):
        return self._values

    values = property(_getValues, _setValues)

    def __init__(self,outstation_ip, outstation_id):
        
        self._soe_handler = SOEHandler()
        self._soe_handler.values = self.values

        log_handler = asiodnp3.ConsoleLogger().Create()

        self._manager = asiodnp3.DNP3Manager(1, log_handler)
        retry = asiopal.ChannelRetry().Default()
        listener = asiodnp3.PrintingChannelListener().Create()
        channel = self._manager.AddTCPClient('client', opendnp3.levels.NOTHING, retry, outstation_ip, '0.0.0.0', 20000, listener)
        master_application = asiodnp3.DefaultMasterApplication().Create()
        stack_config = asiodnp3.MasterStackConfig()
        stack_config.master.responseTimeout = openpal.TimeDuration().Seconds(2)
        stack_config.link.RemoteAddr = outstation_id

        self._master = channel.AddMaster('master', self._soe_handler, master_application, stack_config)


    def open(self):
        
        self._master.Enable()
        self._master.AddClassScan(opendnp3.ClassField().AllClasses(),
                                                          openpal.TimeDuration().Seconds(10),
                                                          opendnp3.TaskConfig().Default())

    def __del__(self):
        channel.Shutdown()
        channel = None
        manager.Shutdown()
        manager = None
```

And the following test code:

```
from dnp3_master import Dnp3_Master
import time

OUTSTATION_IP = "10.2.70.10"
OUTSTATION_ID = 10

def create_Dnp3_Master():
    print("Creating test master")
    newmaster = Dnp3_Master(OUTSTATION_IP,OUTSTATION_ID)
    newmaster.open()

    print("hello")

    while(1):
        time.sleep(2)
        values = newmaster.values
        print('==========================================')
        print(values)

create_Dnp3_Master()
```

Do you have any idea on what is going on?

**Comment by Saleem344** [comment]
> I can't get pydnp3 running on my computer (and the server, MacOS) if I use the library with Python>3.7.
> 
> It works fine on 3.6 but the same code hangs on newer python versions, I tried to compile with newer versions of pybind11 but no luck.
> 
> Weird thing is that it works on ubuntu on python 3.8.5 just fine!
> 
> I have the following dnp3_master.py
> 
> ```
> from pydnp3 import opendnp3, openpal, asiopal, asiodnp3
> import time
> import logging
> 
> class SOEHandler(opendnp3.ISOEHandler):
>     
>     def __init__(self):
>         self._values ={'analog': [],'binary': []}
>         super(SOEHandler, self).__init__()
> 
>     def Process(self, info, values):
>         a_vals = []
>         b_vals = []
>                
>         if (type(values) == opendnp3.ICollectionIndexedAnalog):
>             class BOSVisitor(opendnp3.IVisitorIndexedAnalog):
>                 def __init__(self):
>                     super(BOSVisitor, self).__init__()
>                 def OnValue(self, indexed_instance):
>                     a_vals.append(indexed_instance.value.value)
>             values.Foreach(BOSVisitor())
>             self.values['analog'] = a_vals.copy()
> 
>         if (type(values) == opendnp3.ICollectionIndexedBinary):
>             class BOSVisitorBin(opendnp3.IVisitorIndexedBinary):
>                 def __init__(self):
>                     super(BOSVisitorBin, self).__init__()
>                 def OnValue(self, indexed_instance):
>                     b_vals.append(indexed_instance.value.value)
>             values.Foreach(BOSVisitorBin())
>             print("here")
>             self.values['binary'] = b_vals.copy()
> 
> 
>     def Start(self):
>         # This is implementing an interface, so this function
>         # must be declared.
>         pass
> 
>     def End(self):
>         # This is implementing an interface, so this function
>         # must be declared.
>         pass
> 
> 
> 
> class Dnp3_Master():
>     
>     _values ={'analog': [],'binary': []}
> 
>     def _setValues(self, values):
>         self._values = values
> 
>     def _getValues(self):
>         return self._values
> 
>     values = property(_getValues, _setValues)
> 
>     def __init__(self,outstation_ip, outstation_id):
>         
>         self._soe_handler = SOEHandler()
>         self._soe_handler.values = self.values
> 
>         log_handler = asiodnp3.ConsoleLogger().Create()
> 
>         self._manager = asiodnp3.DNP3Manager(1, log_handler)
>         retry = asiopal.ChannelRetry().Default()
>         listener = asiodnp3.PrintingChannelListener().Create()
>         channel = self._manager.AddTCPClient('client', opendnp3.levels.NOTHING, retry, outstation_ip, '0.0.0.0', 20000, listener)
>         master_application = asiodnp3.DefaultMasterApplication().Create()
>         stack_config = asiodnp3.MasterStackConfig()
>         stack_config.master.responseTimeout = openpal.TimeDuration().Seconds(2)
>         stack_config.link.RemoteAddr = outstation_id
> 
>         self._master = channel.AddMaster('master', self._soe_handler, master_application, stack_config)
> 
> 
>     def open(self):
>         
>         self._master.Enable()
>         self._master.AddClassScan(opendnp3.ClassField().AllClasses(),
>                                                           openpal.TimeDuration().Seconds(10),
>                                                           opendnp3.TaskConfig().Default())
> 
>     def __del__(self):
>         channel.Shutdown()
>         channel = None
>         manager.Shutdown()
>         manager = None
> ```
> 
> And the following test code:
> 
> ```
> from dnp3_master import Dnp3_Master
> import time
> 
> OUTSTATION_IP = "10.2.70.10"
> OUTSTATION_ID = 10
> 
> def create_Dnp3_Master():
>     print("Creating test master")
>     newmaster = Dnp3_Master(OUTSTATION_IP,OUTSTATION_ID)
>     newmaster.open()
> 
>     print("hello")
> 
>     while(1):
>         time.sleep(2)
>         values = newmaster.values
>         print('==========================================')
>         print(values)
> 
> create_Dnp3_Master()
> ```
> 
> Do you have any idea on what is going on?


Hi vitormhenrique,
I have been used the same code as your example but in my ubuntu, with my python 3.8.5  I'm facing the following issues ( https://github.com/garretfick/pydnp3/issues/6 ) do you have any idea how can we solve this issue??

Thank you.

**Comment by peterhinson** [comment]
@vitormhenrique, the [wheels](https://github.com/garretfick/pydnp3/tree/master/wheel) in this repo only target up to Python 3.6 on Mac. You can try building the package under newer versions of Python (3.7-3.9 works for me) using `python setup.py build`. You might need to install a few dnp3 dependencies before it actually compiles, I recall it being sort of a slog the first time.

**Comment by garretfick** [comment]
Feel free (encouraged) to submit the change to include Python 3.7 (and onwards). I'll update the PyPI package once built.

**Comment by vitormhenrique** [comment]
weirdly enough building on a second mac did the trick.

I might be some other stuff wrong on my machine, like cmake version or something else. 

I'm attaching the .whl for the built file for mac os on python 3.84 if anyone else has issues when building it.

[pydnp3-0.1.0-cp38-cp38-macosx_10_15_x86_64.whl.zip](https://github.com/garretfick/pydnp3/files/5826883/pydnp3-0.1.0-cp38-cp38-macosx_10_15_x86_64.whl.zip)
